//
//  DeveloperPreview.swift
//  AirbnbClone
//
//  Created by Melih Dural on 14.06.2024.
//

import Foundation

class DeveloperPreview{
    static let shared = DeveloperPreview()
    
    var listings: [Listing] = [
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "John Smith",
            ownerImageUrl: "host",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 4,
            numberOfBeds: 4,
            numberOfNights: 3,
            imageUrls: ["home4", "home5", "home2", "home1", "home3"],
            pricePerNight: 567,
            latitude: 25.7850,
            longitude: -80.1936,
            address: "124 Main St",
            city: "Miami",
            state: "Florida",
            title: "Miami Villa",
            rating: 4.86,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .pool, .balcony, .laundry, .tv],
            type: .villa
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Alice Johnson",
            ownerImageUrl: "host",
            numberOfBedrooms: 3,
            numberOfBathrooms: 2,
            numberOfGuests: 6,
            numberOfBeds: 3,
            numberOfNights: 2,
            imageUrls: ["home2", "home5", "home3", "home1", "home4"],
            pricePerNight: 450,
            latitude: 34.0522,
            longitude: -118.2437,
            address: "456 Sunset Blvd",
            city: "Los Angeles",
            state: "California",
            title: "LA Apartment",
            rating: 4.75,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .balcony, .kitchen, .laundry, .tv],
            type: .apartment
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "David Brown",
            ownerImageUrl: "host",
            numberOfBedrooms: 5,
            numberOfBathrooms: 4,
            numberOfGuests: 10,
            numberOfBeds: 6,
            numberOfNights: 9,
            imageUrls: ["home1", "home2", "home5", "home3", "home4"],
            pricePerNight: 800,
            latitude: 40.7128,
            longitude: -74.0060,
            address: "789 Broadway",
            city: "New York",
            state: "New York",
            title: "NYC townHouse",
            rating: 4.9,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .kitchen, .laundry],
            type: .townHouse
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Michael Green",
            ownerImageUrl: "host",
            numberOfBedrooms: 3,
            numberOfBathrooms: 2,
            numberOfGuests: 5,
            numberOfBeds: 3,
            numberOfNights: 1,
            imageUrls: ["home3", "home4", "home2", "home5", "home1"],
            pricePerNight: 400,
            latitude: 51.5074,
            longitude: -0.1278,
            address: "123 Baker St",
            city: "London",
            state: "England",
            title: "London Flat",
            rating: 4.8,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .kitchen, .office, .laundry, .tv],
            type: .apartment
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Emma White",
            ownerImageUrl: "host",
            numberOfBedrooms: 2,
            numberOfBathrooms: 1,
            numberOfGuests: 3,
            numberOfBeds: 2,
            numberOfNights: 6,
            imageUrls: ["home1", "home5", "home2", "home4", "home3"],
            pricePerNight: 300,
            latitude: 48.8566,
            longitude: 2.3522,
            address: "456 Champs-Élysées",
            city: "Paris",
            state: "France",
            title: "Paris Apartment",
            rating: 4.7,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
            type: .apartment
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Sophia Williams",
            ownerImageUrl: "host",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 8,
            numberOfBeds: 4,
            numberOfNights: 10,
            imageUrls: ["home3", "home2", "home4", "home5", "home1"],
            pricePerNight: 650,
            latitude: 35.6895,
            longitude: 139.6917,
            address: "789 Shibuya",
            city: "Tokyo",
            state: "Japan",
            title: "Tokyo House",
            rating: 4.85,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .office],
            type: .townHouse
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Olivia Martinez",
            ownerImageUrl: "host",
            numberOfBedrooms: 3,
            numberOfBathrooms: 2,
            numberOfGuests: 6,
            numberOfBeds: 3,
            numberOfNights: 4,
            imageUrls: ["home4", "home1", "home5", "home3", "home2"],
            pricePerNight: 500,
            latitude: 41.9028,
            longitude: 12.4964,
            address: "123 Via Roma",
            city: "Rome",
            state: "Italy",
            title: "Rome Villa",
            rating: 4.8,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .pool, .laundry, .tv],
            type: .villa
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Liam Thompson",
            ownerImageUrl: "host",
            numberOfBedrooms: 2,
            numberOfBathrooms: 2,
            numberOfGuests: 4,
            numberOfBeds: 2,
            numberOfNights: 8,
            imageUrls: ["home5", "home4", "home2", "home1", "home3"],
            pricePerNight: 350,
            latitude: -33.8688,
            longitude: 151.2093,
            address: "456 Sydney St",
            city: "Sydney",
            state: "Australia",
            title: "Sydney Apartment",
            rating: 4.75,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
            type: .apartment
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Mason Harris",
            ownerImageUrl: "host",
            numberOfBedrooms: 5,
            numberOfBathrooms: 4,
            numberOfGuests: 10,
            numberOfBeds: 5,
            numberOfNights: 2,
            imageUrls: ["home3", "home2", "home4", "home5", "home1"],
            pricePerNight: 700,
            latitude: 52.5200,
            longitude: 13.4050,
            address: "789 Alexanderplatz",
            city: "Berlin",
            state: "Germany",
            title: "Berlin townHouse",
            rating: 4.9,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
            type: .townHouse
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "Isabella Lopez",
            ownerImageUrl: "host",
            numberOfBedrooms: 3,
            numberOfBathrooms: 2,
            numberOfGuests: 5,
            numberOfBeds: 3,
            numberOfNights: 5,
            imageUrls: ["home2", "home3", "home5", "home4", "home1"],
            pricePerNight: 450,
            latitude: 37.7749,
            longitude: -122.4194,
            address: "123 Mission St",
            city: "San Francisco",
            state: "California",
            title: "SF Apartment",
            rating: 4.8,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
            type: .apartment
        ),
        .init(
            id: UUID().uuidString,
            ownerUid: UUID().uuidString,
            ownerName: "James Clark",
            ownerImageUrl: "host",
            numberOfBedrooms: 4,
            numberOfBathrooms: 3,
            numberOfGuests: 8,
            numberOfBeds: 4,
            numberOfNights: 3,
            imageUrls: ["home1", "home2", "home3", "home4", "home5"],
            pricePerNight: 600,
            latitude: 40.4168,
            longitude: -3.7038,
            address: "456 Gran Via",
            city: "Madrid",
            state: "Spain",
            title: "Madrid Villa",
            rating: 4.85,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
            type: .villa
        )
    ]    
}
