# Uncomment the next line to define a global platform for your project
#platform :ios, '17.4'

target 'ListApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'FLEX'
  pod 'IQKeyboardManagerSwift'

end
